<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * HTTP caching for the public JSON API.
 *
 * The /api/* corpus (RMF control catalogs, the CCI list, STIG/SCAP summaries,
 * the KEV/IAVM mirror) is reference data that changes at most daily — it is
 * regenerated by bin/refresh-data.sh — yet bulk ingest clients re-pull it
 * continuously. Tagging every successful API response as cacheable lets
 * well-behaved clients (and any shared cache placed in front) reuse or cheaply
 * revalidate a copy instead of re-fetching the full payload every time:
 *
 *  - Cache-Control: public, max-age=3600 — a fetched copy stays fresh for an
 *    hour, so a conforming client won't re-request it at all in that window.
 *  - ETag (a hash of the body) + an automatic 304 — once the freshness window
 *    lapses, a client that sends If-None-Match gets an empty 304 Not Modified
 *    rather than the body again.
 *
 * Runs on kernel.response, after the controller has produced the JSON. Pairs
 * with ApiRateLimitSubscriber: that one throttles abuse, this one removes the
 * reason well-behaved clients hammer in the first place.
 *
 * Two carve-outs:
 *  - /api/stig/tip returns a RANDOM tip per call, so it must never be cached.
 *  - Non-200 responses (errors, and the 429 from ApiRateLimitSubscriber) are
 *    marked no-store so a stale error or throttle notice is never served back.
 */
final class ApiCacheSubscriber implements EventSubscriberInterface
{
    /** Freshness window for cacheable API responses, in seconds (1 hour). */
    private const MAX_AGE = 3600;

    public function onKernelResponse(ResponseEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        $request = $event->getRequest();
        if (!str_starts_with($request->getPathInfo(), '/api')) {
            return;
        }

        $response = $event->getResponse();

        // The randomised "tip" endpoint, anything that isn't a clean 200, and any
        // non-cacheable method (everything but GET/HEAD) must not be cached.
        if ('/api/stig/tip' === $request->getPathInfo()
            || 200 !== $response->getStatusCode()
            || !$request->isMethodCacheable()
        ) {
            $response->headers->set('Cache-Control', 'no-store');
            return;
        }

        // Cacheable reference data: public, time-boxed, and revalidatable by ETag.
        $response->setPublic();
        $response->setMaxAge(self::MAX_AGE);
        $response->setEtag(hash('sha1', (string) $response->getContent()));
        // Keep gzip/identity variants distinct in any shared cache.
        $response->setVary('Accept-Encoding', false);

        // If the client already holds this exact representation (If-None-Match
        // matches the ETag), collapse the body to an empty 304 Not Modified.
        $response->isNotModified($request);
    }

    public static function getSubscribedEvents(): array
    {
        return [KernelEvents::RESPONSE => [['onKernelResponse', 0]]];
    }
}
